/**
 * Seed article data for development without Firestore.
 * 22 articles: 2 per category, 3 for News.
 *
 * @module @buzzy/shared/seeds/seedArticles
 */

/** Full article detail (mirrors ArticleDetail from articleService) */
export interface SeedArticleDetail {
  id: string;
  status: string;
  headline: string;
  tldr: string;
  keyTakeaways: string[];
  buzzyTake: string | null;
  snappySentence: string;
  metaDescription: string;
  seoKeywords: string[];
  imageUrl: string | null;
  imageSource: string;
  sourceTitle: string;
  sourceUrl: string;
  sourcePublisher: string;
  publishedAt: string;
  dateline: string;
  categoryTag: {
    id: string;
    name: string;
    slug: string;
    color: string;
  };
  topicTags: Array<{
    id: string;
    displayName: string;
    slug: string;
  }>;
  engagementScore: number;
  permanentArticlePoints: number;
  viewCount: number;
  likeCount: number;
  commentCount: number;
  shareCount: number;
  slug: string;
  permalink: string;
  schemaMarkup: Record<string, unknown> | null;
  openGraphTags: Record<string, string> | null;
  twitterCardTags: Record<string, string> | null;
  createdAt: string;
}

/** Feed article subset (mirrors FeedArticle from feedService) */
export interface SeedFeedArticle {
  id: string;
  headline: string;
  tldr: string;
  keyTakeaways: string[];
  buzzyTake: string | null;
  snappySentence: string;
  imageUrl: string | null;
  sourcePublisher: string;
  sourceUrl: string;
  publishedAt: string;
  dateline: string;
  categoryTag: {
    id: string;
    name: string;
    slug: string;
    color: string;
  };
  topicTags: Array<{
    id: string;
    displayName: string;
    slug: string;
  }>;
  engagementPoints: number;
  isBookmarked: boolean;
}

/**
 * Maps a full SeedArticleDetail to a SeedFeedArticle.
 *
 * @param article - Full article detail
 * @returns Feed article subset
 */
export function toFeedArticle(article: SeedArticleDetail): SeedFeedArticle {
  return {
    id: article.id,
    headline: article.headline,
    tldr: article.tldr,
    keyTakeaways: article.keyTakeaways,
    buzzyTake: article.buzzyTake,
    snappySentence: article.snappySentence,
    imageUrl: article.imageUrl,
    sourcePublisher: article.sourcePublisher,
    sourceUrl: article.sourceUrl,
    publishedAt: article.publishedAt,
    dateline: article.dateline,
    categoryTag: article.categoryTag,
    topicTags: article.topicTags,
    engagementPoints: article.engagementScore,
    isBookmarked: false,
  };
}

/** Helper to create an ISO date string N hours ago from a fixed reference */
function hoursAgo(n: number): string {
  const d = new Date('2026-03-02T12:00:00Z');
  d.setHours(d.getHours() - n);
  return d.toISOString();
}

export const SEED_ARTICLES: SeedArticleDetail[] = [
  // ── Tech (2) ──
  {
    id: 'seed-tech-1',
    status: 'permanent',
    headline: 'OpenAI Unveils GPT-5: Reasoning Benchmarks Shattered Overnight',
    tldr: "OpenAI's GPT-5 model scores 94% on the ARC-AGI benchmark, doubling GPT-4o's performance and igniting a fierce debate over whether we've crossed the AGI threshold.",
    keyTakeaways: [
      'GPT-5 scores 94% on ARC-AGI, up from 47% for GPT-4o.',
      'The model runs on a new "Orion" architecture with 8x mixture-of-experts.',
      'API pricing starts at $15 per million input tokens — 3x cheaper than GPT-4o at launch.',
    ],
    buzzyTake: 'Whether this is "AGI" depends on who you ask, but one thing is clear: the bar just moved dramatically. Every AI startup is recalculating their moat this morning.',
    snappySentence: 'GPT-5 just turned every AI benchmark into yesterday\'s news.',
    metaDescription: 'OpenAI GPT-5 scores 94% on ARC-AGI benchmark, doubling previous performance.',
    seoKeywords: ['GPT-5', 'OpenAI', 'AGI', 'artificial intelligence', 'benchmark'],
    imageUrl: 'https://picsum.photos/seed/openai-gpt5/800/450',
    imageSource: 'Illustration',
    sourceTitle: 'OpenAI Unveils GPT-5',
    sourceUrl: 'https://example.com/openai-gpt5',
    sourcePublisher: 'The Verge',
    publishedAt: hoursAgo(2),
    dateline: '(SAN FRANCISCO) — Mar. 2, 2026, 10:00 a.m. ET',
    categoryTag: { id: 'cat-tech', name: 'Tech', slug: 'tech', color: '#3C82F6' },
    topicTags: [
      { id: 'tag-openai', displayName: 'OpenAI', slug: 'openai' },
      { id: 'tag-ai', displayName: 'Artificial Intelligence', slug: 'artificial-intelligence' },
    ],
    engagementScore: 9850,
    permanentArticlePoints: 120,
    viewCount: 48200,
    likeCount: 3100,
    commentCount: 412,
    shareCount: 1870,
    slug: 'openai-unveils-gpt5-reasoning-benchmarks-shattered',
    permalink: '/article/openai-unveils-gpt5-reasoning-benchmarks-shattered',
    schemaMarkup: null,
    openGraphTags: null,
    twitterCardTags: null,
    createdAt: hoursAgo(2),
  },
  {
    id: 'seed-tech-2',
    status: 'candidate',
    headline: 'Apple Vision Pro 2 Drops to $1,999 With Prescription Lenses Built In',
    tldr: 'Apple slashes the Vision Pro price by 40% and integrates prescription lenses directly into the headset for its second generation, aiming to crack the mainstream market.',
    keyTakeaways: [
      'Vision Pro 2 starts at $1,999, down from $3,499 for the original.',
      'Built-in prescription lenses eliminate the $149 Zeiss insert accessory.',
      'Apple claims 4 hours of battery life, up from 2 hours on gen 1.',
    ],
    buzzyTake: 'The price cut is aggressive, but $2K is still a lot for something most people will use 20 minutes a day. The prescription lens move is genuinely clever though — it removes the biggest friction point for glasses wearers.',
    snappySentence: 'Apple bets a price cut and built-in lenses can make spatial computing stick.',
    metaDescription: 'Apple Vision Pro 2 launches at $1,999 with built-in prescription lenses.',
    seoKeywords: ['Apple', 'Vision Pro 2', 'mixed reality', 'AR', 'VR'],
    imageUrl: 'https://picsum.photos/seed/apple-vision-pro-2/800/450',
    imageSource: 'Apple',
    sourceTitle: 'Apple Vision Pro 2 Announced',
    sourceUrl: 'https://example.com/apple-vision-pro-2',
    sourcePublisher: 'TechCrunch',
    publishedAt: hoursAgo(5),
    dateline: '(CUPERTINO) — Mar. 2, 2026, 7:00 a.m. ET',
    categoryTag: { id: 'cat-tech', name: 'Tech', slug: 'tech', color: '#3C82F6' },
    topicTags: [
      { id: 'tag-apple', displayName: 'Apple', slug: 'apple' },
      { id: 'tag-vr', displayName: 'Virtual Reality', slug: 'virtual-reality' },
    ],
    engagementScore: 7200,
    permanentArticlePoints: 85,
    viewCount: 31500,
    likeCount: 1800,
    commentCount: 287,
    shareCount: 920,
    slug: 'apple-vision-pro-2-drops-to-1999',
    permalink: '/article/apple-vision-pro-2-drops-to-1999',
    schemaMarkup: null,
    openGraphTags: null,
    twitterCardTags: null,
    createdAt: hoursAgo(5),
  },

  // ── Science (2) ──
  {
    id: 'seed-science-1',
    status: 'permanent',
    headline: 'CRISPR Trial Reverses Sickle Cell Disease in 90% of Patients',
    tldr: 'A landmark Phase III trial shows CRISPR-based gene editing eliminated sickle cell crises in 9 out of 10 patients over 18 months, with the FDA fast-tracking approval.',
    keyTakeaways: [
      '90% of patients had zero sickle cell crises after treatment.',
      'The one-time infusion costs an estimated $2.2 million per patient.',
      'FDA granted breakthrough therapy designation, with approval expected by Q3 2026.',
    ],
    buzzyTake: "This isn't just a treatment — it's a functional cure. The cost is staggering, but so is the lifetime cost of managing sickle cell disease. Insurance math is about to get interesting.",
    snappySentence: 'CRISPR just turned a lifelong disease into a one-time fix for most patients.',
    metaDescription: 'CRISPR gene editing eliminates sickle cell crises in 90% of trial patients.',
    seoKeywords: ['CRISPR', 'sickle cell', 'gene editing', 'clinical trial', 'FDA'],
    imageUrl: 'https://picsum.photos/seed/crispr-sickle-cell/800/450',
    imageSource: 'Science Photo Library',
    sourceTitle: 'CRISPR Sickle Cell Trial Results',
    sourceUrl: 'https://example.com/crispr-sickle-cell',
    sourcePublisher: 'Nature',
    publishedAt: hoursAgo(3),
    dateline: '(BOSTON) — Mar. 2, 2026, 9:00 a.m. ET',
    categoryTag: { id: 'cat-science', name: 'Science', slug: 'science', color: '#10B981' },
    topicTags: [
      { id: 'tag-crispr', displayName: 'CRISPR', slug: 'crispr' },
      { id: 'tag-gene-therapy', displayName: 'Gene Therapy', slug: 'gene-therapy' },
    ],
    engagementScore: 8500,
    permanentArticlePoints: 110,
    viewCount: 39000,
    likeCount: 2700,
    commentCount: 198,
    shareCount: 1540,
    slug: 'crispr-reverses-sickle-cell-disease-90-percent',
    permalink: '/article/crispr-reverses-sickle-cell-disease-90-percent',
    schemaMarkup: null,
    openGraphTags: null,
    twitterCardTags: null,
    createdAt: hoursAgo(3),
  },
  {
    id: 'seed-science-2',
    status: 'candidate',
    headline: 'James Webb Telescope Detects Signs of Life-Supporting Atmosphere on Nearby Exoplanet',
    tldr: 'JWST spectroscopy reveals methane and carbon dioxide in the atmosphere of K2-18b, a super-Earth 120 light-years away, consistent with a water ocean and potentially habitable conditions.',
    keyTakeaways: [
      'Methane and CO2 detected at confidence levels above 5 sigma.',
      'Dimethyl sulfide — a molecule only produced by life on Earth — tentatively detected at 2.5 sigma.',
      'K2-18b orbits in the habitable zone of a red dwarf star.',
    ],
    buzzyTake: "Before you break out the 'we are not alone' banners: the DMS detection is weak and needs confirmation. But the methane+CO2 combo is genuinely exciting. This is exactly the kind of planet JWST was built to study.",
    snappySentence: 'Webb just found the most promising hint of alien life yet — but scientists urge patience.',
    metaDescription: 'James Webb Telescope finds potential biosignatures on exoplanet K2-18b.',
    seoKeywords: ['James Webb', 'exoplanet', 'K2-18b', 'biosignature', 'astronomy'],
    imageUrl: 'https://picsum.photos/seed/jwst-k218b/800/450',
    imageSource: 'NASA/ESA',
    sourceTitle: 'JWST K2-18b Atmosphere Results',
    sourceUrl: 'https://example.com/jwst-k218b',
    sourcePublisher: 'NASA',
    publishedAt: hoursAgo(8),
    dateline: '(WASHINGTON) — Mar. 2, 2026, 4:00 a.m. ET',
    categoryTag: { id: 'cat-science', name: 'Science', slug: 'science', color: '#10B981' },
    topicTags: [
      { id: 'tag-space', displayName: 'Space', slug: 'space' },
      { id: 'tag-jwst', displayName: 'James Webb Telescope', slug: 'james-webb-telescope' },
    ],
    engagementScore: 6800,
    permanentArticlePoints: 75,
    viewCount: 28000,
    likeCount: 2100,
    commentCount: 156,
    shareCount: 1100,
    slug: 'jwst-detects-life-supporting-atmosphere-exoplanet',
    permalink: '/article/jwst-detects-life-supporting-atmosphere-exoplanet',
    schemaMarkup: null,
    openGraphTags: null,
    twitterCardTags: null,
    createdAt: hoursAgo(8),
  },

  // ── Health (2) ──
  {
    id: 'seed-health-1',
    status: 'permanent',
    headline: 'Ozempic Maker Launches Once-Monthly Weight Loss Injection in Phase III',
    tldr: "Novo Nordisk's CagriSema, a once-monthly GLP-1 injection, achieves 25% body weight loss in trials — the highest of any obesity drug — challenging the weekly Ozempic regimen.",
    keyTakeaways: [
      'CagriSema achieved 25% average weight loss at 68 weeks.',
      'Monthly dosing vs weekly could dramatically improve adherence.',
      'Novo Nordisk stock jumped 8% on the announcement.',
    ],
    buzzyTake: 'The GLP-1 arms race just went monthly. If insurance coverage follows, this could be the drug that finally normalizes medical weight management. The convenience factor alone is a game-changer.',
    snappySentence: 'A once-a-month shot just set a new record for weight loss — and Wall Street noticed.',
    metaDescription: 'Novo Nordisk CagriSema achieves 25% weight loss with monthly injection.',
    seoKeywords: ['Ozempic', 'GLP-1', 'weight loss', 'CagriSema', 'Novo Nordisk'],
    imageUrl: 'https://picsum.photos/seed/cagrisema-monthly/800/450',
    imageSource: 'Reuters',
    sourceTitle: 'CagriSema Phase III Results',
    sourceUrl: 'https://example.com/cagrisema',
    sourcePublisher: 'Reuters',
    publishedAt: hoursAgo(4),
    dateline: '(COPENHAGEN) — Mar. 2, 2026, 8:00 a.m. ET',
    categoryTag: { id: 'cat-health', name: 'Health', slug: 'health', color: '#8554F6' },
    topicTags: [
      { id: 'tag-glp1', displayName: 'GLP-1 Drugs', slug: 'glp1-drugs' },
      { id: 'tag-pharma', displayName: 'Pharmaceuticals', slug: 'pharmaceuticals' },
    ],
    engagementScore: 7800,
    permanentArticlePoints: 95,
    viewCount: 35000,
    likeCount: 2200,
    commentCount: 340,
    shareCount: 1200,
    slug: 'ozempic-maker-launches-monthly-weight-loss-injection',
    permalink: '/article/ozempic-maker-launches-monthly-weight-loss-injection',
    schemaMarkup: null,
    openGraphTags: null,
    twitterCardTags: null,
    createdAt: hoursAgo(4),
  },
  {
    id: 'seed-health-2',
    status: 'candidate',
    headline: 'CDC Reports Record Drop in U.S. Overdose Deaths for Second Straight Year',
    tldr: 'Drug overdose deaths fell 18% in 2025 to 72,000 — the lowest since 2019 — driven by expanded access to naloxone and fentanyl test strips in 38 states.',
    keyTakeaways: [
      'Overdose deaths fell from 88,000 in 2024 to 72,000 in 2025.',
      'Naloxone distribution increased 340% year-over-year.',
      'Fentanyl-related deaths still account for 68% of all overdose deaths.',
    ],
    buzzyTake: "The harm reduction approach is working — slowly. Critics will say 72,000 deaths is still a crisis, and they're right. But the trend line matters, and this one is finally pointing the right way.",
    snappySentence: 'Overdose deaths hit a 6-year low as harm reduction scales nationwide.',
    metaDescription: 'U.S. drug overdose deaths fall 18% in 2025 to lowest level since 2019.',
    seoKeywords: ['overdose', 'CDC', 'naloxone', 'fentanyl', 'harm reduction'],
    imageUrl: 'https://picsum.photos/seed/cdc-overdose-drop/800/450',
    imageSource: 'CDC',
    sourceTitle: 'CDC Overdose Death Statistics 2025',
    sourceUrl: 'https://example.com/cdc-overdose',
    sourcePublisher: 'Washington Post',
    publishedAt: hoursAgo(10),
    dateline: '(ATLANTA) — Mar. 1, 2026, 2:00 p.m. ET',
    categoryTag: { id: 'cat-health', name: 'Health', slug: 'health', color: '#8554F6' },
    topicTags: [
      { id: 'tag-opioids', displayName: 'Opioid Crisis', slug: 'opioid-crisis' },
      { id: 'tag-public-health', displayName: 'Public Health', slug: 'public-health' },
    ],
    engagementScore: 5200,
    permanentArticlePoints: 60,
    viewCount: 22000,
    likeCount: 1400,
    commentCount: 189,
    shareCount: 780,
    slug: 'cdc-record-drop-overdose-deaths-2025',
    permalink: '/article/cdc-record-drop-overdose-deaths-2025',
    schemaMarkup: null,
    openGraphTags: null,
    twitterCardTags: null,
    createdAt: hoursAgo(10),
  },

  // ── Sports (2) ──
  {
    id: 'seed-sports-1',
    status: 'permanent',
    headline: 'Caitlin Clark Drops 51 Points as Fever Clinch Top Playoff Seed',
    tldr: 'Caitlin Clark scored a career-high 51 points against the Aces, clinching the #1 seed for Indiana and breaking the single-game WNBA scoring record in the process.',
    keyTakeaways: [
      'Clark scored 51 points on 17-of-28 shooting with 8 three-pointers.',
      'She broke Diana Taurasi\'s single-game record of 47 points.',
      'The Fever finished 29-11 to clinch the top seed in the playoffs.',
    ],
    buzzyTake: 'The WNBA ratings machine keeps delivering. Clark isn\'t just good — she has a flair for the dramatic that turns regular-season games into appointment television.',
    snappySentence: 'Caitlin Clark rewrote the WNBA record book with a 51-point masterclass.',
    metaDescription: 'Caitlin Clark scores career-high 51 points, breaks WNBA single-game record.',
    seoKeywords: ['Caitlin Clark', 'WNBA', 'Indiana Fever', 'scoring record', 'basketball'],
    imageUrl: 'https://picsum.photos/seed/caitlin-clark-51/800/450',
    imageSource: 'Getty Images',
    sourceTitle: 'Clark Drops 51 in Record Night',
    sourceUrl: 'https://example.com/caitlin-clark-51',
    sourcePublisher: 'ESPN',
    publishedAt: hoursAgo(6),
    dateline: '(INDIANAPOLIS) — Mar. 2, 2026, 6:00 a.m. ET',
    categoryTag: { id: 'cat-sports', name: 'Sports', slug: 'sports', color: '#F59E09' },
    topicTags: [
      { id: 'tag-wnba', displayName: 'WNBA', slug: 'wnba' },
      { id: 'tag-basketball', displayName: 'Basketball', slug: 'basketball' },
    ],
    engagementScore: 8900,
    permanentArticlePoints: 100,
    viewCount: 42000,
    likeCount: 3400,
    commentCount: 512,
    shareCount: 2100,
    slug: 'caitlin-clark-51-points-fever-clinch-top-seed',
    permalink: '/article/caitlin-clark-51-points-fever-clinch-top-seed',
    schemaMarkup: null,
    openGraphTags: null,
    twitterCardTags: null,
    createdAt: hoursAgo(6),
  },
  {
    id: 'seed-sports-2',
    status: 'candidate',
    headline: 'FIFA Confirms 2030 World Cup Will Use AI-Powered Offside and Foul Detection',
    tldr: 'FIFA announced that the 2030 World Cup in Spain, Portugal, and Morocco will deploy fully automated AI refereeing for offside calls and foul detection — eliminating VAR delays.',
    keyTakeaways: [
      'AI will make offside and foul decisions in under 0.5 seconds.',
      'Human referees will remain for subjective calls like yellow/red cards.',
      '12 stadiums will be fitted with 200+ tracking cameras each.',
    ],
    buzzyTake: 'VAR was supposed to fix refereeing, but it broke the flow of the game. If AI can deliver instant, accurate calls, it might actually fulfill VAR\'s original promise without the three-minute pauses.',
    snappySentence: 'FIFA bets AI can do what VAR couldn\'t — get calls right without killing the vibe.',
    metaDescription: 'FIFA announces AI-powered refereeing for 2030 World Cup offside and foul calls.',
    seoKeywords: ['FIFA', 'World Cup 2030', 'AI refereeing', 'VAR', 'soccer'],
    imageUrl: 'https://picsum.photos/seed/fifa-ai-referee/800/450',
    imageSource: 'FIFA',
    sourceTitle: 'FIFA 2030 AI Refereeing',
    sourceUrl: 'https://example.com/fifa-ai-referee',
    sourcePublisher: 'BBC Sport',
    publishedAt: hoursAgo(12),
    dateline: '(ZURICH) — Mar. 1, 2026, 12:00 p.m. ET',
    categoryTag: { id: 'cat-sports', name: 'Sports', slug: 'sports', color: '#F59E09' },
    topicTags: [
      { id: 'tag-fifa', displayName: 'FIFA', slug: 'fifa' },
      { id: 'tag-soccer', displayName: 'Soccer', slug: 'soccer' },
    ],
    engagementScore: 5600,
    permanentArticlePoints: 65,
    viewCount: 25000,
    likeCount: 1500,
    commentCount: 230,
    shareCount: 890,
    slug: 'fifa-2030-world-cup-ai-offside-foul-detection',
    permalink: '/article/fifa-2030-world-cup-ai-offside-foul-detection',
    schemaMarkup: null,
    openGraphTags: null,
    twitterCardTags: null,
    createdAt: hoursAgo(12),
  },

  // ── Entertainment (2) ──
  {
    id: 'seed-entertainment-1',
    status: 'permanent',
    headline: 'Beyoncé Announces "Renaissance World Tour II" With Holographic Stage Design',
    tldr: 'Beyoncé revealed a 60-date world tour featuring a 360-degree holographic stage, AI-generated visuals that react to crowd energy, and ticket prices starting at $75.',
    keyTakeaways: [
      'The tour kicks off August 2026 with 60 dates across 5 continents.',
      'Holographic projections create a "no bad seats" experience in arenas.',
      'Standard tickets start at $75, with VIP packages up to $2,500.',
    ],
    buzzyTake: 'Beyoncé at the intersection of live music and tech wizardry is exactly the kind of arms race that benefits fans. The $75 starting price is a deliberate shot at Ticketmaster\'s dynamic pricing playbook.',
    snappySentence: 'Beyoncé is bringing holograms to stadiums — and keeping ticket prices human.',
    metaDescription: 'Beyoncé Renaissance World Tour II features holographic stage and $75 ticket prices.',
    seoKeywords: ['Beyoncé', 'Renaissance Tour', 'concert', 'holographic', 'tour dates'],
    imageUrl: 'https://picsum.photos/seed/beyonce-tour-ii/800/450',
    imageSource: 'Parkwood Entertainment',
    sourceTitle: 'Beyoncé World Tour II Announcement',
    sourceUrl: 'https://example.com/beyonce-tour',
    sourcePublisher: 'Rolling Stone',
    publishedAt: hoursAgo(7),
    dateline: '(LOS ANGELES) — Mar. 2, 2026, 5:00 a.m. ET',
    categoryTag: { id: 'cat-entertainment', name: 'Entertainment', slug: 'entertainment', color: '#EC4999' },
    topicTags: [
      { id: 'tag-music', displayName: 'Music', slug: 'music' },
      { id: 'tag-concerts', displayName: 'Concerts', slug: 'concerts' },
    ],
    engagementScore: 7500,
    permanentArticlePoints: 90,
    viewCount: 55000,
    likeCount: 4200,
    commentCount: 380,
    shareCount: 2800,
    slug: 'beyonce-renaissance-world-tour-ii-holographic-stage',
    permalink: '/article/beyonce-renaissance-world-tour-ii-holographic-stage',
    schemaMarkup: null,
    openGraphTags: null,
    twitterCardTags: null,
    createdAt: hoursAgo(7),
  },
  {
    id: 'seed-entertainment-2',
    status: 'candidate',
    headline: 'Marvel Announces "Avengers: Secret Wars" Will Be Shot Entirely With Virtual Production',
    tldr: 'Marvel Studios confirmed that Avengers: Secret Wars will use a next-gen virtual production stage three times the size of The Volume, with AI-generated environments rendered in real time.',
    keyTakeaways: [
      'The new "Nexus Stage" is 12,000 sq ft — triple The Mandalorian\'s Volume.',
      'AI renders photorealistic environments in real time, eliminating green screen.',
      'Secret Wars is scheduled for May 2027 with a $400M budget.',
    ],
    buzzyTake: "After the VFX artist burnout controversy, Marvel going all-in on virtual production is either the fix or more of the same. The tech is impressive — the question is whether it actually improves working conditions.",
    snappySentence: "Marvel's biggest movie ever will be made inside a giant LED room powered by AI.",
    metaDescription: 'Avengers Secret Wars to use next-gen virtual production stage with AI rendering.',
    seoKeywords: ['Avengers', 'Secret Wars', 'Marvel', 'virtual production', 'MCU'],
    imageUrl: 'https://picsum.photos/seed/marvel-secret-wars/800/450',
    imageSource: 'Marvel Studios',
    sourceTitle: 'Secret Wars Virtual Production',
    sourceUrl: 'https://example.com/secret-wars',
    sourcePublisher: 'Variety',
    publishedAt: hoursAgo(14),
    dateline: '(LOS ANGELES) — Mar. 1, 2026, 10:00 a.m. ET',
    categoryTag: { id: 'cat-entertainment', name: 'Entertainment', slug: 'entertainment', color: '#EC4999' },
    topicTags: [
      { id: 'tag-marvel', displayName: 'Marvel', slug: 'marvel' },
      { id: 'tag-movies', displayName: 'Movies', slug: 'movies' },
    ],
    engagementScore: 6200,
    permanentArticlePoints: 70,
    viewCount: 38000,
    likeCount: 2600,
    commentCount: 445,
    shareCount: 1600,
    slug: 'marvel-avengers-secret-wars-virtual-production',
    permalink: '/article/marvel-avengers-secret-wars-virtual-production',
    schemaMarkup: null,
    openGraphTags: null,
    twitterCardTags: null,
    createdAt: hoursAgo(14),
  },

  // ── Politics (2) ──
  {
    id: 'seed-politics-1',
    status: 'permanent',
    headline: 'Bipartisan Bill Would Ban Members of Congress From Trading Individual Stocks',
    tldr: 'A rare bipartisan coalition in the Senate introduced the TRUST Act, which would require all members of Congress to divest individual stock holdings within 6 months or face escalating fines.',
    keyTakeaways: [
      'The TRUST Act has 12 Republican and 14 Democratic co-sponsors.',
      'Members would have 180 days to move holdings into blind trusts or index funds.',
      'Violations would incur fines starting at $10,000, doubling for each repeat offense.',
    ],
    buzzyTake: "We've seen this movie before — congressional stock trading bills that get introduced, get attention, then quietly die. But 26 co-sponsors is the most any version has had. Public pressure might finally outweigh self-interest.",
    snappySentence: 'Congress might finally ban itself from trading stocks — if it can resist the irony.',
    metaDescription: 'Bipartisan TRUST Act would ban members of Congress from trading individual stocks.',
    seoKeywords: ['Congress', 'stock trading ban', 'TRUST Act', 'bipartisan', 'ethics'],
    imageUrl: 'https://picsum.photos/seed/congress-stock-ban/800/450',
    imageSource: 'AP',
    sourceTitle: 'TRUST Act Congressional Stock Ban',
    sourceUrl: 'https://example.com/trust-act',
    sourcePublisher: 'Politico',
    publishedAt: hoursAgo(9),
    dateline: '(WASHINGTON) — Mar. 2, 2026, 3:00 a.m. ET',
    categoryTag: { id: 'cat-politics', name: 'Politics', slug: 'politics', color: '#6467F1' },
    topicTags: [
      { id: 'tag-congress', displayName: 'Congress', slug: 'congress' },
      { id: 'tag-ethics', displayName: 'Government Ethics', slug: 'government-ethics' },
    ],
    engagementScore: 7100,
    permanentArticlePoints: 88,
    viewCount: 33000,
    likeCount: 2900,
    commentCount: 520,
    shareCount: 1450,
    slug: 'bipartisan-bill-ban-congress-stock-trading',
    permalink: '/article/bipartisan-bill-ban-congress-stock-trading',
    schemaMarkup: null,
    openGraphTags: null,
    twitterCardTags: null,
    createdAt: hoursAgo(9),
  },
  {
    id: 'seed-politics-2',
    status: 'candidate',
    headline: 'Supreme Court to Hear Challenge to State-Level Social Media Age Verification Laws',
    tldr: 'The Supreme Court agreed to hear a case challenging state laws requiring age verification for social media, with implications for online privacy, free speech, and parental rights.',
    keyTakeaways: [
      '18 states have passed social media age verification laws since 2024.',
      'Tech companies argue the laws violate the First Amendment.',
      'Oral arguments are set for October 2026.',
    ],
    buzzyTake: "This case will define the internet for the next decade. If the Court sides with states, we'll see ID verification everywhere. If it sides with tech, the 'protect the kids' movement loses its biggest tool.",
    snappySentence: 'The Supreme Court will decide whether states can card you to use Instagram.',
    metaDescription: 'Supreme Court to rule on constitutionality of social media age verification laws.',
    seoKeywords: ['Supreme Court', 'social media', 'age verification', 'First Amendment', 'privacy'],
    imageUrl: 'https://picsum.photos/seed/scotus-social-media/800/450',
    imageSource: 'Reuters',
    sourceTitle: 'SCOTUS Social Media Age Verification',
    sourceUrl: 'https://example.com/scotus-social',
    sourcePublisher: 'CNN',
    publishedAt: hoursAgo(15),
    dateline: '(WASHINGTON) — Mar. 1, 2026, 9:00 a.m. ET',
    categoryTag: { id: 'cat-politics', name: 'Politics', slug: 'politics', color: '#6467F1' },
    topicTags: [
      { id: 'tag-scotus', displayName: 'Supreme Court', slug: 'supreme-court' },
      { id: 'tag-privacy', displayName: 'Digital Privacy', slug: 'digital-privacy' },
    ],
    engagementScore: 4800,
    permanentArticlePoints: 55,
    viewCount: 19000,
    likeCount: 1100,
    commentCount: 310,
    shareCount: 680,
    slug: 'supreme-court-social-media-age-verification',
    permalink: '/article/supreme-court-social-media-age-verification',
    schemaMarkup: null,
    openGraphTags: null,
    twitterCardTags: null,
    createdAt: hoursAgo(15),
  },

  // ── Money (2) ──
  {
    id: 'seed-money-1',
    status: 'permanent',
    headline: 'Fed Signals June Rate Cut as Inflation Hits 2.1% Target',
    tldr: 'Federal Reserve Chair signaled the first rate cut in 18 months is likely in June after PCE inflation fell to 2.1%, the closest to the 2% target since 2020.',
    keyTakeaways: [
      'PCE inflation hit 2.1% in February, down from 2.8% in December.',
      'Markets now price a 92% chance of a 25bp cut in June.',
      'The 10-year Treasury yield fell to 3.8% on the news.',
    ],
    buzzyTake: "The rate cut everybody's been waiting for is finally in sight. Mortgage rates should follow — but don't expect a housing price drop. Pent-up demand will absorb cheaper rates almost instantly.",
    snappySentence: 'The Fed just gave the clearest rate-cut signal in over a year — June is on.',
    metaDescription: 'Federal Reserve signals June rate cut as PCE inflation reaches 2.1% target.',
    seoKeywords: ['Federal Reserve', 'rate cut', 'inflation', 'PCE', 'interest rates'],
    imageUrl: 'https://picsum.photos/seed/fed-rate-cut-june/800/450',
    imageSource: 'Bloomberg',
    sourceTitle: 'Fed Signals June Rate Cut',
    sourceUrl: 'https://example.com/fed-rate-cut',
    sourcePublisher: 'Bloomberg',
    publishedAt: hoursAgo(1),
    dateline: '(WASHINGTON) — Mar. 2, 2026, 11:00 a.m. ET',
    categoryTag: { id: 'cat-money', name: 'Money', slug: 'money', color: '#059669' },
    topicTags: [
      { id: 'tag-fed', displayName: 'Federal Reserve', slug: 'federal-reserve' },
      { id: 'tag-inflation', displayName: 'Inflation', slug: 'inflation' },
    ],
    engagementScore: 8200,
    permanentArticlePoints: 105,
    viewCount: 45000,
    likeCount: 2800,
    commentCount: 290,
    shareCount: 1700,
    slug: 'fed-signals-june-rate-cut-inflation-2-percent',
    permalink: '/article/fed-signals-june-rate-cut-inflation-2-percent',
    schemaMarkup: null,
    openGraphTags: null,
    twitterCardTags: null,
    createdAt: hoursAgo(1),
  },
  {
    id: 'seed-money-2',
    status: 'candidate',
    headline: 'Gen Z Is Saving More Than Millennials Did at the Same Age, New Data Shows',
    tldr: 'A Federal Reserve study found that adults ages 18-27 have a median savings rate of 12% of income, compared to 8% for Millennials at the same age — driven by fintech apps and TikTok financial literacy.',
    keyTakeaways: [
      'Gen Z median savings rate is 12%, vs 8% for Millennials at the same age.',
      '73% of Gen Z respondents use at least one fintech savings app.',
      'Student loan debt is lower due to income-driven repayment expansion.',
    ],
    buzzyTake: 'The "Gen Z is broke" narrative keeps colliding with data that says otherwise. Turns out watching TikTok finance creators actually teaches you something. Who knew?',
    snappySentence: 'Gen Z is quietly out-saving Millennials — and TikTok might be why.',
    metaDescription: 'Federal Reserve data shows Gen Z saves 12% of income vs 8% for Millennials.',
    seoKeywords: ['Gen Z', 'savings', 'personal finance', 'fintech', 'millennials'],
    imageUrl: 'https://picsum.photos/seed/genz-saving-more/800/450',
    imageSource: 'Federal Reserve',
    sourceTitle: 'Gen Z Savings Rate Study',
    sourceUrl: 'https://example.com/genz-savings',
    sourcePublisher: 'Wall Street Journal',
    publishedAt: hoursAgo(16),
    dateline: '(NEW YORK) — Mar. 1, 2026, 8:00 a.m. ET',
    categoryTag: { id: 'cat-money', name: 'Money', slug: 'money', color: '#059669' },
    topicTags: [
      { id: 'tag-genz', displayName: 'Gen Z', slug: 'gen-z' },
      { id: 'tag-personal-finance', displayName: 'Personal Finance', slug: 'personal-finance' },
    ],
    engagementScore: 5100,
    permanentArticlePoints: 58,
    viewCount: 21000,
    likeCount: 1600,
    commentCount: 280,
    shareCount: 950,
    slug: 'gen-z-saving-more-than-millennials',
    permalink: '/article/gen-z-saving-more-than-millennials',
    schemaMarkup: null,
    openGraphTags: null,
    twitterCardTags: null,
    createdAt: hoursAgo(16),
  },

  // ── Crypto (2) ──
  {
    id: 'seed-crypto-1',
    status: 'permanent',
    headline: 'Ethereum Completes "Pectra" Upgrade, Slashing Gas Fees by 90%',
    tldr: "Ethereum's long-awaited Pectra upgrade went live today, reducing average gas fees from $2.50 to $0.25 and introducing native account abstraction for wallet-less dApp interactions.",
    keyTakeaways: [
      'Average gas fees dropped from $2.50 to $0.25 within 2 hours of activation.',
      'EIP-7702 enables dApps to sponsor gas fees for users.',
      'Validator staking rewards decreased 15% as part of the issuance reduction.',
    ],
    buzzyTake: "Gas fees were Ethereum's biggest UX problem. At $0.25, it's finally cheap enough that normal people won't rage-quit a transaction. Account abstraction is the sleeper feature that could onboard the next 100M users.",
    snappySentence: 'Ethereum just made gas fees an afterthought — and wallets optional.',
    metaDescription: 'Ethereum Pectra upgrade reduces gas fees 90% and introduces account abstraction.',
    seoKeywords: ['Ethereum', 'Pectra', 'gas fees', 'EIP-7702', 'blockchain'],
    imageUrl: 'https://picsum.photos/seed/ethereum-pectra/800/450',
    imageSource: 'CoinDesk',
    sourceTitle: 'Ethereum Pectra Upgrade Live',
    sourceUrl: 'https://example.com/ethereum-pectra',
    sourcePublisher: 'CoinDesk',
    publishedAt: hoursAgo(3),
    dateline: '(NEW YORK) — Mar. 2, 2026, 9:00 a.m. ET',
    categoryTag: { id: 'cat-crypto', name: 'Crypto', slug: 'crypto', color: '#F9751A' },
    topicTags: [
      { id: 'tag-ethereum', displayName: 'Ethereum', slug: 'ethereum' },
      { id: 'tag-defi', displayName: 'DeFi', slug: 'defi' },
    ],
    engagementScore: 7600,
    permanentArticlePoints: 92,
    viewCount: 36000,
    likeCount: 2500,
    commentCount: 310,
    shareCount: 1350,
    slug: 'ethereum-pectra-upgrade-slashes-gas-fees-90-percent',
    permalink: '/article/ethereum-pectra-upgrade-slashes-gas-fees-90-percent',
    schemaMarkup: null,
    openGraphTags: null,
    twitterCardTags: null,
    createdAt: hoursAgo(3),
  },
  {
    id: 'seed-crypto-2',
    status: 'candidate',
    headline: 'SEC Approves First Solana Spot ETF — Trading Begins Monday',
    tldr: 'The SEC approved VanEck\'s Solana spot ETF application, making SOL the third cryptocurrency with a U.S. spot ETF after Bitcoin and Ethereum. SOL price surged 22% on the news.',
    keyTakeaways: [
      "VanEck's Solana Trust ETF approved with 0.20% expense ratio.",
      'SOL price jumped from $180 to $220 in after-hours trading.',
      'BlackRock and Fidelity are expected to file competing Solana ETFs within weeks.',
    ],
    buzzyTake: 'The crypto ETF floodgates are officially open. Solana getting approved before XRP or Cardano is a signal that the SEC is looking at actual usage and developer activity, not just market cap.',
    snappySentence: 'Solana just got the Wall Street seal of approval — spot ETF starts Monday.',
    metaDescription: 'SEC approves first Solana spot ETF from VanEck, SOL price surges 22%.',
    seoKeywords: ['Solana', 'ETF', 'SEC', 'VanEck', 'cryptocurrency'],
    imageUrl: 'https://picsum.photos/seed/solana-spot-etf/800/450',
    imageSource: 'Bloomberg',
    sourceTitle: 'SEC Approves Solana ETF',
    sourceUrl: 'https://example.com/solana-etf',
    sourcePublisher: 'Bloomberg',
    publishedAt: hoursAgo(11),
    dateline: '(WASHINGTON) — Mar. 1, 2026, 1:00 p.m. ET',
    categoryTag: { id: 'cat-crypto', name: 'Crypto', slug: 'crypto', color: '#F9751A' },
    topicTags: [
      { id: 'tag-solana', displayName: 'Solana', slug: 'solana' },
      { id: 'tag-etf', displayName: 'ETF', slug: 'etf' },
    ],
    engagementScore: 6400,
    permanentArticlePoints: 72,
    viewCount: 29000,
    likeCount: 2000,
    commentCount: 270,
    shareCount: 1100,
    slug: 'sec-approves-solana-spot-etf',
    permalink: '/article/sec-approves-solana-spot-etf',
    schemaMarkup: null,
    openGraphTags: null,
    twitterCardTags: null,
    createdAt: hoursAgo(11),
  },

  // ── News (3) ──
  {
    id: 'seed-news-1',
    status: 'permanent',
    headline: 'Magnitude 7.1 Earthquake Hits Central Turkey — Rescue Operations Underway',
    tldr: 'A powerful 7.1 magnitude earthquake struck central Turkey early this morning, collapsing buildings in three provinces. At least 40 confirmed dead with thousands feared trapped.',
    keyTakeaways: [
      'The 7.1 quake struck at 3:14 a.m. local time, 20 km south of Kayseri.',
      'Buildings collapsed in Kayseri, Nevşehir, and Aksaray provinces.',
      'International rescue teams from 8 countries have been deployed.',
    ],
    buzzyTake: 'Three years after the devastating 2023 quakes killed 50,000, Turkey\'s earthquake preparedness is being tested again. Early reports suggest newer buildings with updated codes fared better — but "better" is cold comfort for those trapped.',
    snappySentence: 'Turkey faces another deadly earthquake — international rescue teams race to respond.',
    metaDescription: 'Magnitude 7.1 earthquake strikes central Turkey, rescue operations underway.',
    seoKeywords: ['Turkey', 'earthquake', 'Kayseri', 'rescue', 'natural disaster'],
    imageUrl: 'https://picsum.photos/seed/turkey-earthquake-71/800/450',
    imageSource: 'AFP',
    sourceTitle: 'Turkey Earthquake Breaking Coverage',
    sourceUrl: 'https://example.com/turkey-earthquake',
    sourcePublisher: 'AP News',
    publishedAt: hoursAgo(1),
    dateline: '(KAYSERI, Turkey) — Mar. 2, 2026, 11:00 a.m. ET',
    categoryTag: { id: 'cat-news', name: 'News', slug: 'news', color: '#EF4040' },
    topicTags: [
      { id: 'tag-earthquake', displayName: 'Earthquake', slug: 'earthquake' },
      { id: 'tag-turkey', displayName: 'Turkey', slug: 'turkey' },
    ],
    engagementScore: 9200,
    permanentArticlePoints: 115,
    viewCount: 52000,
    likeCount: 1200,
    commentCount: 340,
    shareCount: 3200,
    slug: 'magnitude-71-earthquake-central-turkey-rescue',
    permalink: '/article/magnitude-71-earthquake-central-turkey-rescue',
    schemaMarkup: null,
    openGraphTags: null,
    twitterCardTags: null,
    createdAt: hoursAgo(1),
  },
  {
    id: 'seed-news-2',
    status: 'permanent',
    headline: 'EU Passes Landmark AI Liability Directive — Companies Face Strict Penalties',
    tldr: 'The European Parliament voted 412-89 to pass the AI Liability Directive, making companies strictly liable for harm caused by AI systems and requiring mandatory insurance for high-risk deployments.',
    keyTakeaways: [
      'Companies deploying high-risk AI must carry mandatory liability insurance.',
      'Fines up to 6% of global annual revenue for non-compliance.',
      'The directive takes effect January 2027 with a 12-month grace period.',
    ],
    buzzyTake: 'Europe keeps writing the rulebook for AI while America debates whether to write one at all. Whether these rules help citizens or just push innovation to other jurisdictions remains the trillion-euro question.',
    snappySentence: 'Europe just made AI companies legally responsible when their systems cause harm.',
    metaDescription: 'EU passes AI Liability Directive requiring mandatory insurance and strict penalties.',
    seoKeywords: ['EU', 'AI regulation', 'AI liability', 'technology policy', 'Europe'],
    imageUrl: 'https://picsum.photos/seed/eu-ai-liability/800/450',
    imageSource: 'European Parliament',
    sourceTitle: 'EU AI Liability Directive Passes',
    sourceUrl: 'https://example.com/eu-ai-liability',
    sourcePublisher: 'Financial Times',
    publishedAt: hoursAgo(6),
    dateline: '(BRUSSELS) — Mar. 2, 2026, 6:00 a.m. ET',
    categoryTag: { id: 'cat-news', name: 'News', slug: 'news', color: '#EF4040' },
    topicTags: [
      { id: 'tag-eu', displayName: 'European Union', slug: 'european-union' },
      { id: 'tag-ai-regulation', displayName: 'AI Regulation', slug: 'ai-regulation' },
    ],
    engagementScore: 6900,
    permanentArticlePoints: 82,
    viewCount: 27000,
    likeCount: 1800,
    commentCount: 290,
    shareCount: 1050,
    slug: 'eu-ai-liability-directive-strict-penalties',
    permalink: '/article/eu-ai-liability-directive-strict-penalties',
    schemaMarkup: null,
    openGraphTags: null,
    twitterCardTags: null,
    createdAt: hoursAgo(6),
  },
  {
    id: 'seed-news-3',
    status: 'candidate',
    headline: 'Global Coral Reef Recovery Detected for First Time in Satellite Record',
    tldr: 'NOAA satellite data reveals a 3.2% increase in global coral cover over the past 18 months — the first net recovery since monitoring began in 1985 — attributed to marine protected areas and cooler La Niña conditions.',
    keyTakeaways: [
      'Global coral cover increased 3.2% between mid-2024 and early 2026.',
      'The Great Barrier Reef saw its largest recovery in 30 years.',
      'Scientists warn the gains are fragile and could reverse with the next El Niño.',
    ],
    buzzyTake: "Good news is so rare in climate reporting that it's almost suspicious. But the data is solid: marine protected areas work, and cooler water helps. The challenge is whether we can sustain this through the next warm cycle.",
    snappySentence: 'For the first time ever, satellite data shows coral reefs are growing back.',
    metaDescription: 'NOAA reports first global coral reef recovery in satellite monitoring history.',
    seoKeywords: ['coral reef', 'ocean', 'NOAA', 'climate', 'marine conservation'],
    imageUrl: 'https://picsum.photos/seed/coral-reef-recovery/800/450',
    imageSource: 'NOAA',
    sourceTitle: 'Global Coral Recovery Report',
    sourceUrl: 'https://example.com/coral-recovery',
    sourcePublisher: 'National Geographic',
    publishedAt: hoursAgo(18),
    dateline: '(MIAMI) — Mar. 1, 2026, 6:00 a.m. ET',
    categoryTag: { id: 'cat-news', name: 'News', slug: 'news', color: '#EF4040' },
    topicTags: [
      { id: 'tag-climate', displayName: 'Climate', slug: 'climate' },
      { id: 'tag-ocean', displayName: 'Oceans', slug: 'oceans' },
    ],
    engagementScore: 4500,
    permanentArticlePoints: 50,
    viewCount: 18000,
    likeCount: 2200,
    commentCount: 130,
    shareCount: 1400,
    slug: 'global-coral-reef-recovery-first-time-satellite',
    permalink: '/article/global-coral-reef-recovery-first-time-satellite',
    schemaMarkup: null,
    openGraphTags: null,
    twitterCardTags: null,
    createdAt: hoursAgo(18),
  },

  // ── Markets (2) ──
  {
    id: 'seed-markets-1',
    status: 'permanent',
    headline: 'S&P 500 Hits All-Time High as Tech Rally Extends to 8th Straight Week',
    tldr: 'The S&P 500 closed at 5,842 on Friday, marking its 8th consecutive weekly gain, driven by AI-related earnings beats from Nvidia, Microsoft, and Alphabet.',
    keyTakeaways: [
      'S&P 500 closed at 5,842 — a new all-time high.',
      'Nvidia reported $38B quarterly revenue, beating estimates by 12%.',
      'Market breadth improved with 78% of S&P 500 stocks above their 200-day MA.',
    ],
    buzzyTake: 'Eight weeks of gains usually triggers "bubble" talk, but the breadth numbers tell a different story. This isn\'t just 7 mega-caps dragging the index up — nearly 4 in 5 stocks are in uptrends.',
    snappySentence: 'The S&P 500 hit another record as the AI-fueled rally refuses to quit.',
    metaDescription: 'S&P 500 reaches all-time high at 5,842 on 8th consecutive weekly gain.',
    seoKeywords: ['S&P 500', 'stock market', 'Nvidia', 'tech rally', 'all-time high'],
    imageUrl: 'https://picsum.photos/seed/sp500-record-high/800/450',
    imageSource: 'CNBC',
    sourceTitle: 'S&P 500 New Record Close',
    sourceUrl: 'https://example.com/sp500-record',
    sourcePublisher: 'CNBC',
    publishedAt: hoursAgo(4),
    dateline: '(NEW YORK) — Mar. 2, 2026, 8:00 a.m. ET',
    categoryTag: { id: 'cat-markets', name: 'Markets', slug: 'markets', color: '#2B4C95' },
    topicTags: [
      { id: 'tag-sp500', displayName: 'S&P 500', slug: 'sp500' },
      { id: 'tag-nvidia', displayName: 'Nvidia', slug: 'nvidia' },
    ],
    engagementScore: 6800,
    permanentArticlePoints: 80,
    viewCount: 31000,
    likeCount: 1900,
    commentCount: 210,
    shareCount: 980,
    slug: 'sp500-all-time-high-tech-rally-8-weeks',
    permalink: '/article/sp500-all-time-high-tech-rally-8-weeks',
    schemaMarkup: null,
    openGraphTags: null,
    twitterCardTags: null,
    createdAt: hoursAgo(4),
  },
  {
    id: 'seed-markets-2',
    status: 'candidate',
    headline: 'Oil Drops Below $60 as OPEC+ Fails to Agree on Production Cuts',
    tldr: 'Brent crude fell below $60 for the first time since 2021 after OPEC+ members failed to agree on production cuts, with Saudi Arabia and the UAE at odds over quota allocations.',
    keyTakeaways: [
      'Brent crude dropped to $58.40, the lowest since November 2021.',
      'Saudi Arabia wanted 1M barrel/day cuts; UAE pushed for higher quotas.',
      'U.S. shale producers are profitable down to $45/barrel, limiting OPEC leverage.',
    ],
    buzzyTake: 'Cheap oil is great for consumers and terrible for petrostates. OPEC\'s inability to agree is a structural problem — each member needs high prices, but nobody wants to be the one who pumps less.',
    snappySentence: 'OPEC+ infighting just gave consumers the cheapest oil in four years.',
    metaDescription: 'Brent crude falls below $60 as OPEC+ fails to agree on production cuts.',
    seoKeywords: ['oil', 'OPEC', 'crude', 'energy', 'commodities'],
    imageUrl: 'https://picsum.photos/seed/oil-below-60/800/450',
    imageSource: 'Reuters',
    sourceTitle: 'Oil Below $60 on OPEC Failure',
    sourceUrl: 'https://example.com/oil-opec',
    sourcePublisher: 'Reuters',
    publishedAt: hoursAgo(13),
    dateline: '(LONDON) — Mar. 1, 2026, 11:00 a.m. ET',
    categoryTag: { id: 'cat-markets', name: 'Markets', slug: 'markets', color: '#2B4C95' },
    topicTags: [
      { id: 'tag-oil', displayName: 'Oil', slug: 'oil' },
      { id: 'tag-opec', displayName: 'OPEC', slug: 'opec' },
    ],
    engagementScore: 5400,
    permanentArticlePoints: 62,
    viewCount: 23000,
    likeCount: 1300,
    commentCount: 180,
    shareCount: 750,
    slug: 'oil-drops-below-60-opec-fails-production-cuts',
    permalink: '/article/oil-drops-below-60-opec-fails-production-cuts',
    schemaMarkup: null,
    openGraphTags: null,
    twitterCardTags: null,
    createdAt: hoursAgo(13),
  },

  // ── Lifestyle (2) ──
  {
    id: 'seed-lifestyle-1',
    status: 'permanent',
    headline: '"Dopamine Menus" Are Replacing Doom Scrolling — Here\'s How They Work',
    tldr: "A viral wellness trend has people creating personalized 'dopamine menus' — curated lists of healthy mood-boosting activities ranked by effort level — as an intentional replacement for phone-based dopamine hits.",
    keyTakeaways: [
      'The #DopamineMenu hashtag has 2.1 billion views on TikTok.',
      'Menus are organized into "appetizers" (easy), "entrees" (medium), and "desserts" (splurge).',
      'Psychologists say the framework works because it provides structure for intention.',
    ],
    buzzyTake: "Is it silly to make a menu of fun things to do instead of scrolling? Maybe. Is it working for millions of people? Definitely. Sometimes the simplest frameworks are the most powerful.",
    snappySentence: 'Millions are swapping doom scrolling for curated joy — one "dopamine menu" at a time.',
    metaDescription: 'Dopamine menus trend replaces doom scrolling with curated mood-boosting activities.',
    seoKeywords: ['dopamine menu', 'wellness', 'doom scrolling', 'mental health', 'TikTok'],
    imageUrl: 'https://picsum.photos/seed/dopamine-menu-trend/800/450',
    imageSource: 'Getty Images',
    sourceTitle: 'Dopamine Menu Trend Explained',
    sourceUrl: 'https://example.com/dopamine-menu',
    sourcePublisher: 'Vox',
    publishedAt: hoursAgo(8),
    dateline: '(NEW YORK) — Mar. 2, 2026, 4:00 a.m. ET',
    categoryTag: { id: 'cat-lifestyle', name: 'Lifestyle', slug: 'lifestyle', color: '#DA4BF0' },
    topicTags: [
      { id: 'tag-wellness', displayName: 'Wellness', slug: 'wellness' },
      { id: 'tag-mental-health', displayName: 'Mental Health', slug: 'mental-health' },
    ],
    engagementScore: 6100,
    permanentArticlePoints: 68,
    viewCount: 41000,
    likeCount: 3800,
    commentCount: 220,
    shareCount: 2400,
    slug: 'dopamine-menus-replacing-doom-scrolling',
    permalink: '/article/dopamine-menus-replacing-doom-scrolling',
    schemaMarkup: null,
    openGraphTags: null,
    twitterCardTags: null,
    createdAt: hoursAgo(8),
  },
  {
    id: 'seed-lifestyle-2',
    status: 'candidate',
    headline: 'Japan\'s New "Digital Nomad Village" Offers Free Housing for Remote Workers',
    tldr: "A rural Japanese town is offering free housing for up to 1 year to remote workers who commit to spending at least $500/month locally, in an effort to combat depopulation.",
    keyTakeaways: [
      'Kamiyama, Tokushima prefecture is providing 50 renovated homes at no rent.',
      "Participants must earn remotely and spend ≥$500/month at local businesses.",
      'The program includes Japanese language classes and cultural immersion.',
    ],
    buzzyTake: "Japan's depopulation crisis is creating opportunities that sound too good to be true. Free housing in a beautiful mountain town? The catch is you actually have to, you know, live there. For many remote workers, that's not a catch — it's the dream.",
    snappySentence: 'A Japanese mountain town is giving away free houses to remote workers willing to stay.',
    metaDescription: 'Kamiyama, Japan offers free housing to remote workers to combat depopulation.',
    seoKeywords: ['Japan', 'digital nomad', 'remote work', 'free housing', 'depopulation'],
    imageUrl: 'https://picsum.photos/seed/japan-nomad-village/800/450',
    imageSource: 'Kyodo News',
    sourceTitle: 'Japan Digital Nomad Village',
    sourceUrl: 'https://example.com/japan-nomad',
    sourcePublisher: 'Japan Times',
    publishedAt: hoursAgo(20),
    dateline: '(TOKUSHIMA, Japan) — Mar. 1, 2026, 4:00 a.m. ET',
    categoryTag: { id: 'cat-lifestyle', name: 'Lifestyle', slug: 'lifestyle', color: '#DA4BF0' },
    topicTags: [
      { id: 'tag-remote-work', displayName: 'Remote Work', slug: 'remote-work' },
      { id: 'tag-japan', displayName: 'Japan', slug: 'japan' },
    ],
    engagementScore: 4900,
    permanentArticlePoints: 52,
    viewCount: 35000,
    likeCount: 3200,
    commentCount: 190,
    shareCount: 2100,
    slug: 'japan-digital-nomad-village-free-housing',
    permalink: '/article/japan-digital-nomad-village-free-housing',
    schemaMarkup: null,
    openGraphTags: null,
    twitterCardTags: null,
    createdAt: hoursAgo(20),
  },
];
