/**
 * Seed comment data for development without Firestore.
 * 3-5 comments for the first 8 seed articles.
 *
 * @module @buzzy/shared/seeds/seedComments
 */

/** Comment DTO (mirrors CommentDTO from commentService) */
export interface SeedCommentDTO {
  id: string;
  articleId: string;
  userId: string;
  username: string;
  displayName: string;
  avatarUrl: string | null;
  content: string;
  likeCount: number;
  isTopTake: boolean;
  isLikedByUser: boolean;
  createdAt: string;
  updatedAt: string;
}

/** Seed comments keyed by article ID */
export const SEED_COMMENTS: Record<string, SeedCommentDTO[]> = {
  'seed-tech-1': [
    {
      id: 'comment-1a',
      articleId: 'seed-tech-1',
      userId: 'user-sam',
      username: 'samdev',
      displayName: 'Sam Chen',
      avatarUrl: null,
      content: 'The ARC-AGI jump is wild but I want to see real-world coding benchmarks before calling this AGI. Benchmarks ≠ intelligence.',
      likeCount: 42,
      isTopTake: true,
      isLikedByUser: false,
      createdAt: '2026-03-02T10:30:00Z',
      updatedAt: '2026-03-02T10:30:00Z',
    },
    {
      id: 'comment-1b',
      articleId: 'seed-tech-1',
      userId: 'user-maya',
      username: 'mayaresearch',
      displayName: 'Maya Patel',
      avatarUrl: null,
      content: 'The pricing is the real story here. $15/M tokens makes GPT-5 cheaper than GPT-4o was at launch. That\'s going to accelerate adoption massively.',
      likeCount: 28,
      isTopTake: false,
      isLikedByUser: false,
      createdAt: '2026-03-02T10:45:00Z',
      updatedAt: '2026-03-02T10:45:00Z',
    },
    {
      id: 'comment-1c',
      articleId: 'seed-tech-1',
      userId: 'user-alex',
      username: 'alexk',
      displayName: 'Alex Kim',
      avatarUrl: null,
      content: 'Every AI startup just had an emergency meeting this morning. If your moat was "fine-tuned GPT-4," your moat just evaporated.',
      likeCount: 35,
      isTopTake: false,
      isLikedByUser: false,
      createdAt: '2026-03-02T11:00:00Z',
      updatedAt: '2026-03-02T11:00:00Z',
    },
  ],
  'seed-tech-2': [
    {
      id: 'comment-2a',
      articleId: 'seed-tech-2',
      userId: 'user-jordan',
      username: 'jordanvr',
      displayName: 'Jordan Rivera',
      avatarUrl: null,
      content: 'I returned my gen 1 after a month. The prescription lens thing alone might get me to try again — fumbling with Zeiss inserts was awful.',
      likeCount: 19,
      isTopTake: false,
      isLikedByUser: false,
      createdAt: '2026-03-02T08:00:00Z',
      updatedAt: '2026-03-02T08:00:00Z',
    },
    {
      id: 'comment-2b',
      articleId: 'seed-tech-2',
      userId: 'user-taylor',
      username: 'taylorux',
      displayName: 'Taylor Lee',
      avatarUrl: null,
      content: '$2K is still a lot but it\'s in "serious gadget" territory now instead of "luxury toy" territory. I think this moves the needle.',
      likeCount: 12,
      isTopTake: false,
      isLikedByUser: false,
      createdAt: '2026-03-02T08:30:00Z',
      updatedAt: '2026-03-02T08:30:00Z',
    },
    {
      id: 'comment-2c',
      articleId: 'seed-tech-2',
      userId: 'user-casey',
      username: 'caseydev',
      displayName: 'Casey Wright',
      avatarUrl: null,
      content: '4 hours of battery! That\'s actually usable for a work session now. Gen 1 at 2 hours was basically a demo unit.',
      likeCount: 8,
      isTopTake: false,
      isLikedByUser: false,
      createdAt: '2026-03-02T09:15:00Z',
      updatedAt: '2026-03-02T09:15:00Z',
    },
  ],
  'seed-science-1': [
    {
      id: 'comment-3a',
      articleId: 'seed-science-1',
      userId: 'user-dr-j',
      username: 'drjohnson',
      displayName: 'Dr. R. Johnson',
      avatarUrl: null,
      content: 'As a hematologist — this is the most significant advance in sickle cell treatment since hydroxyurea in the 90s. The cost is the barrier, not the science.',
      likeCount: 67,
      isTopTake: true,
      isLikedByUser: false,
      createdAt: '2026-03-02T09:30:00Z',
      updatedAt: '2026-03-02T09:30:00Z',
    },
    {
      id: 'comment-3b',
      articleId: 'seed-science-1',
      userId: 'user-nina',
      username: 'ninahealth',
      displayName: 'Nina Okafor',
      avatarUrl: null,
      content: '$2.2M sounds crazy but the lifetime cost of managing SCD is $1.6M+ with much worse quality of life. Insurance companies should be lining up.',
      likeCount: 45,
      isTopTake: false,
      isLikedByUser: false,
      createdAt: '2026-03-02T09:45:00Z',
      updatedAt: '2026-03-02T09:45:00Z',
    },
    {
      id: 'comment-3c',
      articleId: 'seed-science-1',
      userId: 'user-ravi',
      username: 'ravibio',
      displayName: 'Ravi Sharma',
      avatarUrl: null,
      content: 'The real question is global access. Sickle cell disproportionately affects sub-Saharan Africa where $2.2M per patient is impossible.',
      likeCount: 38,
      isTopTake: false,
      isLikedByUser: false,
      createdAt: '2026-03-02T10:00:00Z',
      updatedAt: '2026-03-02T10:00:00Z',
    },
    {
      id: 'comment-3d',
      articleId: 'seed-science-1',
      userId: 'user-kim',
      username: 'kimgenetics',
      displayName: 'Kim Tanaka',
      avatarUrl: null,
      content: 'Phase III at 90% is remarkable. Most gene therapies struggle past 60-70%. Whatever Vertex did with their delivery vector is working.',
      likeCount: 22,
      isTopTake: false,
      isLikedByUser: false,
      createdAt: '2026-03-02T10:15:00Z',
      updatedAt: '2026-03-02T10:15:00Z',
    },
  ],
  'seed-science-2': [
    {
      id: 'comment-4a',
      articleId: 'seed-science-2',
      userId: 'user-astro',
      username: 'astrodave',
      displayName: 'Dave Kowalski',
      avatarUrl: null,
      content: '2.5 sigma on DMS is not a detection — it\'s a hint. We need 5 sigma minimum. But methane + CO2 at >5 sigma is legitimately exciting.',
      likeCount: 31,
      isTopTake: true,
      isLikedByUser: false,
      createdAt: '2026-03-02T05:00:00Z',
      updatedAt: '2026-03-02T05:00:00Z',
    },
    {
      id: 'comment-4b',
      articleId: 'seed-science-2',
      userId: 'user-luna',
      username: 'lunastars',
      displayName: 'Luna Rodriguez',
      avatarUrl: null,
      content: 'K2-18b is a "Hycean world" — basically a giant ocean with a hydrogen atmosphere. Very different from Earth but life could look very different too.',
      likeCount: 18,
      isTopTake: false,
      isLikedByUser: false,
      createdAt: '2026-03-02T05:30:00Z',
      updatedAt: '2026-03-02T05:30:00Z',
    },
    {
      id: 'comment-4c',
      articleId: 'seed-science-2',
      userId: 'user-pete',
      username: 'petestargazer',
      displayName: 'Pete Nakamura',
      avatarUrl: null,
      content: 'JWST keeps delivering. Every few months it finds something that would have been a career-defining discovery 20 years ago.',
      likeCount: 24,
      isTopTake: false,
      isLikedByUser: false,
      createdAt: '2026-03-02T06:00:00Z',
      updatedAt: '2026-03-02T06:00:00Z',
    },
  ],
  'seed-sports-1': [
    {
      id: 'comment-5a',
      articleId: 'seed-sports-1',
      userId: 'user-hoops',
      username: 'hoopsfan99',
      displayName: 'Marcus Thompson',
      avatarUrl: null,
      content: '51 POINTS. 8 threes. Record broken. And she did it in a clinching game. Caitlin Clark is built different.',
      likeCount: 89,
      isTopTake: true,
      isLikedByUser: false,
      createdAt: '2026-03-02T06:30:00Z',
      updatedAt: '2026-03-02T06:30:00Z',
    },
    {
      id: 'comment-5b',
      articleId: 'seed-sports-1',
      userId: 'user-diana',
      username: 'dianafan',
      displayName: 'Sarah Mitchell',
      avatarUrl: null,
      content: "Taurasi's record lasted 18 years. I have a feeling Clark's might last longer — she set it so high.",
      likeCount: 34,
      isTopTake: false,
      isLikedByUser: false,
      createdAt: '2026-03-02T07:00:00Z',
      updatedAt: '2026-03-02T07:00:00Z',
    },
    {
      id: 'comment-5c',
      articleId: 'seed-sports-1',
      userId: 'user-bball',
      username: 'courtside_j',
      displayName: 'Jamal White',
      avatarUrl: null,
      content: 'WNBA ratings have tripled since Clark entered the league. She doesn\'t just score — she sells out arenas and moves TV numbers.',
      likeCount: 52,
      isTopTake: false,
      isLikedByUser: false,
      createdAt: '2026-03-02T07:30:00Z',
      updatedAt: '2026-03-02T07:30:00Z',
    },
  ],
  'seed-entertainment-1': [
    {
      id: 'comment-6a',
      articleId: 'seed-entertainment-1',
      userId: 'user-bey',
      username: 'beyhive_jade',
      displayName: 'Jade Williams',
      avatarUrl: null,
      content: '$75 starting price?? Beyoncé said Ticketmaster is NOT going to price out the fans this time. Queen behavior.',
      likeCount: 76,
      isTopTake: true,
      isLikedByUser: false,
      createdAt: '2026-03-02T05:30:00Z',
      updatedAt: '2026-03-02T05:30:00Z',
    },
    {
      id: 'comment-6b',
      articleId: 'seed-entertainment-1',
      userId: 'user-music',
      username: 'concertjunkie',
      displayName: 'Ryan Park',
      avatarUrl: null,
      content: 'Holographic projections that react to crowd energy? This is the future of live music. Every other artist is going to be scrambling to copy this.',
      likeCount: 33,
      isTopTake: false,
      isLikedByUser: false,
      createdAt: '2026-03-02T06:00:00Z',
      updatedAt: '2026-03-02T06:00:00Z',
    },
    {
      id: 'comment-6c',
      articleId: 'seed-entertainment-1',
      userId: 'user-live',
      username: 'stagecraft_pro',
      displayName: 'Mike Gonzalez',
      avatarUrl: null,
      content: 'As a stage designer — 360-degree holographic in arena-scale is an engineering nightmare. If they actually pull this off, it changes the industry.',
      likeCount: 21,
      isTopTake: false,
      isLikedByUser: false,
      createdAt: '2026-03-02T06:45:00Z',
      updatedAt: '2026-03-02T06:45:00Z',
    },
  ],
  'seed-politics-1': [
    {
      id: 'comment-7a',
      articleId: 'seed-politics-1',
      userId: 'user-pol',
      username: 'dcinsider',
      displayName: 'Chris Matthews',
      avatarUrl: null,
      content: '26 co-sponsors is promising but we\'ve been here before. The STOCK Act of 2012 had bipartisan support too and got gutted in implementation.',
      likeCount: 55,
      isTopTake: true,
      isLikedByUser: false,
      createdAt: '2026-03-02T04:00:00Z',
      updatedAt: '2026-03-02T04:00:00Z',
    },
    {
      id: 'comment-7b',
      articleId: 'seed-politics-1',
      userId: 'user-vote',
      username: 'voter_first',
      displayName: 'Amy Zhang',
      avatarUrl: null,
      content: 'The fact that we need a law to prevent elected officials from insider trading tells you everything about the system.',
      likeCount: 88,
      isTopTake: false,
      isLikedByUser: false,
      createdAt: '2026-03-02T04:30:00Z',
      updatedAt: '2026-03-02T04:30:00Z',
    },
    {
      id: 'comment-7c',
      articleId: 'seed-politics-1',
      userId: 'user-finance',
      username: 'wallst_watchdog',
      displayName: 'Tom Barrett',
      avatarUrl: null,
      content: 'Blind trusts and index funds is the right approach. You can still build wealth — you just can\'t pick individual winners while having legislative power over those companies.',
      likeCount: 41,
      isTopTake: false,
      isLikedByUser: false,
      createdAt: '2026-03-02T05:00:00Z',
      updatedAt: '2026-03-02T05:00:00Z',
    },
    {
      id: 'comment-7d',
      articleId: 'seed-politics-1',
      userId: 'user-skeptic',
      username: 'political_skeptic',
      displayName: 'Dana Burke',
      avatarUrl: null,
      content: 'Watch the co-sponsors carefully. Some will quietly withdraw when it gets to committee. That\'s always how these things die.',
      likeCount: 29,
      isTopTake: false,
      isLikedByUser: false,
      createdAt: '2026-03-02T05:30:00Z',
      updatedAt: '2026-03-02T05:30:00Z',
    },
  ],
  'seed-money-1': [
    {
      id: 'comment-8a',
      articleId: 'seed-money-1',
      userId: 'user-econ',
      username: 'econ_nerd',
      displayName: 'Prof. Linda Torres',
      avatarUrl: null,
      content: '2.1% PCE is almost exactly the target. The Fed has been patient and it paid off. June cut is the right call — they should have moved in March.',
      likeCount: 37,
      isTopTake: true,
      isLikedByUser: false,
      createdAt: '2026-03-02T11:30:00Z',
      updatedAt: '2026-03-02T11:30:00Z',
    },
    {
      id: 'comment-8b',
      articleId: 'seed-money-1',
      userId: 'user-mortgage',
      username: 'homebuyer2026',
      displayName: 'James Cooper',
      avatarUrl: null,
      content: "Been waiting 2 years to buy a house. If mortgage rates drop below 6%, I'm finally jumping in. Please let this be real.",
      likeCount: 52,
      isTopTake: false,
      isLikedByUser: false,
      createdAt: '2026-03-02T11:45:00Z',
      updatedAt: '2026-03-02T11:45:00Z',
    },
    {
      id: 'comment-8c',
      articleId: 'seed-money-1',
      userId: 'user-bear',
      username: 'contrarian_bear',
      displayName: 'Elena Vasquez',
      avatarUrl: null,
      content: 'One month of 2.1% doesn\'t erase two years of elevated inflation. The Fed should wait for 3 consecutive months below 2.5% before cutting.',
      likeCount: 19,
      isTopTake: false,
      isLikedByUser: false,
      createdAt: '2026-03-02T12:00:00Z',
      updatedAt: '2026-03-02T12:00:00Z',
    },
  ],
};
